name: Build binaries and Upload to Release

on:
  push:
    branches: [ main ]
    paths:
      - "version"
  workflow_dispatch: {}
  
jobs:
  build_Windows_job:
    name: build_Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
  
      - name: Install dependencies and ToolDelta Build
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          pyinstaller -F ToolDelta.py
  
      - name: Convert certificate and sign binary
        shell: pwsh
        run: |
          & "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\pvk2pfx.exe" -pvk cert/ToolDelta.pvk -spc cert/ToolDelta.spc -pfx cert/ToolDelta.pfx -po 123456
          & "C:\Program Files (x86)\Windows Kits\10\bin\x64\10.0.19041.0\signtool.exe" sign /f cert/ToolDelta.pfx /p 123456 /tr http://timestamp.digicert.com /td sha256 /fd sha256 /a dist/ToolDelta.exe
  
      - name: Get version
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: echo "::set-env name=VERSION::$(more version)"
  
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.VERSION}}
          name: ${{env.VERSION}}
          files: |
            dist/*
  build_Linux_job:
        name: build_Linux
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v4
            with:
              python-version: '3.11' 
  
          - name: Install dependencies and ToolDelta Build
            run: |
              python -m pip install --upgrade pip
              pip install pyinstaller
              pip install -r requirements.txt
              pyinstaller -F ToolDelta.py
          - name: Get version
            env:
              ACTIONS_ALLOW_UNSECURE_COMMANDS: true
            run: echo "::set-env name=VERSION::$(cat version)"
  
          - name: Release
            uses: softprops/action-gh-release@v1
            with:
              tag_name: ${{env.VERSION}}
              name: ${{env.VERSION}}
              files: |
                dist/*
