name: Generate Directory JSON

on:
  push:
    branches: [main]
    paths:
      - "plugin_market/**"
  workflow_dispatch: {}

jobs:
  generate_json:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" # 你想要使用的 Python 版本

      - name: Generate JSON
        run: python plugin_market/get_directory.py

      - name: Submit Changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "[AUTO] Generate Directory JSON"
          add: '["plugin_market/directory.json","plugin_market/latest_versions.json"]'
