name: Build and Publish Python Package



on:
  push:
    branches: [ main ]
    paths:
      - "version"
  workflow_dispatch: {}



jobs:
  Publisher:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4.1.1
    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Build and Publish
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
        poetry version $(cat version)
        poetry build
        poetry publish